### ISSUE TITLE
Trying to install but getting open3d installation error

### ISSUE THREAD

**Issue by RoyAmoyal** [psetinek/seathru_nerf#2]
Hey, I am trying to install your project after installing nerfstudio. 

I tried both python 3.8 and python 3.9 on a conda env but I am keep getting the error:
![image](https://github.com/AkerBP/seathru_nerf/assets/69425073/fd761798-88ca-47cf-b981-2e0e784c3c03)

I tried to install newer version of open3d but:
![image](https://github.com/AkerBP/seathru_nerf/assets/69425073/f885cc16-8cbd-4e75-89e5-fca4347e4c15)

I think I can't install open3d on our GPU cluster in my university because of the open3d library. Any way to use your code without open3d and without installing it? 
Thanks

**Comment by psetinek** [comment]
Hi, I saw you posted another processing related issue. Did you manage the installation?
