### ISSUE TITLE
Anyway to process the images (like downscale) without ffmpega and just using OpenCV/PIL?

### ISSUE THREAD

**Issue by RoyAmoyal** [psetinek/seathru_nerf#3]
Hey, I can't install FFMPEGon my PC, and I want to use your github method. anyway to do the processing without FFMPEG?

**Comment by psetinek** [comment]
Hi!

Is this just for preprocessing, i.e. computing camera poses? If yes, there are methods supported by nerfstudio that do not use ffmpeg (see https://docs.nerf.studio/quickstart/custom_dataset.html). However when you want to render a video from a trained nerf, you will still need ffmpeg:/
