### ISSUE TITLE
Request for Pretrained Models & Test Configs on the SeaThru NerF Datasets

### ISSUE THREAD

**Issue by ShaohuaL** [psetinek/seathru_nerf#4]
Could you kindly share the pretrained models for SeaThru NerF Datasets along with the test set configurations used in your awesome  work?

**Comment by psetinek** [comment]
Hi @ShaohuaL! Sorry for the late reply. Happy to share my pretrained models with checkpoints etc. If you contact me via paul.setinek@gmail.com I will share.
