### ISSUE TITLE
clear scene image

### ISSUE THREAD

**Issue by ZhenWusi** [psetinek/seathru_nerf#5]
Pls how can I only see my clear scene image, I need dewater-enhanced image for 3DGS reconstruction。

**Comment by psetinek** [comment]
In the live viewer during training you have options what to render. For the clear scene you can select "J". This is also an option when rendering a video from a pretraing. You can also checkout the documentation here to get a nice walkthrough of all the options: [documentation.](https://akerbp.github.io/seathru_nerf/usage.html#rendering)

**Comment by ZhenWusi** [comment]
I can't do without the video, just the original picture after the water is removed

**Comment by ZhenWusi** [comment]
I don't want a video, just a picture of the original picture after removing the water？Thank you so much

**Comment by psetinek** [comment]
Okay, then training a NeRF would be a bit of an overkill. The underlying image formation model you can find [here](https://paperswithcode.com/paper/sea-thru-a-method-for-removing-water-from). You could try out the two implementations listed there.
